### ISSUE TITLE
Fill Read ME

### ISSUE THREAD

**Issue by paulmontecot** [marinemnrd/Covid_Dash_OpenSource#10]
- [x] Project Title
- [x] Project Description
- [x] Installation
- [x] Working instructions
- [x] Made With
- [x] Authors
- [x] License

**Comment by marinemnrd** [comment]
## What's done 
Project Title and Description are done :raised_hands:

**Comment by marinemnrd** [comment]
## Questions
Can someone take care of the Installation ? :pray:

**Comment by paulmontecot** [comment]
Sure !

**Comment by paulmontecot** [comment]
Done !
