### ISSUE TITLE
Project List

### ISSUE THREAD

**Issue by marinemnrd** [marinemnrd/Covid_Dash_OpenSource#11]
## Metadata

- [x] The README.md file is present at the root of the GitHub repo.
- [x] The README.md file states where the data come from (with a link to the original repo).
- [x] The README.md file contains guidelines to explicitly install all required dependencies for the project.
- [x] The README.md file contains instructions on how to locally run the dashboard.
- [x] The LICENSE file contains a valid open-source license.
- [x] The requirements.txt (for pip) or environment.yml (for conda) file to install all required dependencies at once.

## Organization

- [x] Issues are created to list expected features and report bugs.
- [x] Issues are discussed.
- [x] Commits address implementation of one feature or fix of one bug at a time.
- [x] Commits are (roughly) evenly distributed among project participants.
- [x] New features are implemented in branches and merged through pull requests.

## Visualization

- [x] Dashboard displays graphics of Covid-19 cases or deaths vs time.
- [x] Dashboard displays graphics of Covid-19 cases or deaths for several countries.
- [x] Data are normalized with respect to the number of inhabitants per country.
- [x] Peak (wave) detection is implemented.

## Interaction

- [x] User can select which country to display (among a predefined list of countries).
- [x] User can display many countries in the same graphic.
- [x] User can select the color of the line.
- [x] User can select to display Covid-19 cases or deaths.
- [x] User can select the time frame to display.

**Comment by paulmontecot** [comment]
Nice ! I added The presentation of the Project and the Data Provider repo's link :)

**Comment by Lily87-hub** [comment]
Issue completed.

**Comment by paulmontecot** [comment]
Perfect
