### ISSUE TITLE
 Create requirement.txt for installing all the Packages

### ISSUE THREAD

**Issue by paulmontecot** [marinemnrd/Covid_Dash_OpenSource#12]

**Comment by marinemnrd** [comment]
@Lily87-hub I can help you with this ! Send me what you did :kissing_heart:

**Comment by Lily87-hub** [comment]
> @Lily87-hub I can help you with this ! Send me what you did 😘

Ok thanks, here is doc I am working on before putting it in the Repo; https://docs.google.com/document/d/1qS71NDzU0b0nnHag7Pw79NfvTuYToisBjEMsNqyDgAM/edit#

**Comment by Lily87-hub** [comment]
Completed.
