### ISSUE TITLE
Link to the web app does not work

### ISSUE THREAD

**Issue by pierrepo** [marinemnrd/Covid_Dash_OpenSource#23]
Hello :wave: 
The link to the web app in the `README.me` file looks wrong 

> The project is Hosted by streamlit. You can also clic on this link to visualize the dashboard.

**Comment by marinemnrd** [comment]
Can we fix that now that we have the link? @paulmontecot  @Lily87-hub

**Comment by Lily87-hub** [comment]
> Hello 👋
> The link to the web app in the `README.me` file looks wrong
> 
> > The project is Hosted by streamlit. You can also clic on this link to visualize the dashboard.

We have made corrections to the README.md.

**Comment by marinemnrd** [comment]
> > Hello 👋
> > The link to the web app in the `README.me` file looks wrong
> > > The project is Hosted by streamlit. You can also clic on this link to visualize the dashboard.
> 
> We have made corrections to the README.md.

It still doesn't work tho, can I have the link so I can display it in another way? Thanks :two_hearts:

**Comment by pierrepo** [comment]
Can you put here, in this thread, the link to Streamlit sharing?

**Comment by Lily87-hub** [comment]
> Can you put here, in this thread, the link to Streamlit sharing?

Here is the link;
https://share.streamlit.io/paulmontecot/covid_dash_opensource/main/main.py

**Comment by pierrepo** [comment]
So here is what you have to put in your `README.md` file:
```
The project is hosted by Streamlit. You can also clic on this [link](https://share.streamlit.io/paulmontecot/covid_dash_opensource/main/main.py) to visualize the dashboard.
```

**Comment by Lily87-hub** [comment]
> So here is what you have to put in your `README.md` file:
> 
> ```
> The project is hosted by Streamlit. You can also clic on this [link](https://share.streamlit.io/paulmontecot/covid_dash_opensource/main/main.py) to visualize the dashboard.
> ```

Done!

**Comment by paulmontecot** [comment]
Finally Working !
